name: ContinuousD - Publica√ß√£o da aplica√ß√£o ao Azure Container App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Executando o Job de Publica√ß√£o
    runs-on: ubuntu-latest

    steps:
      - name: Clonagem do c√≥digo fonte
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: 'marioguilhermedev'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t marioguilhermedev/fiapcloudgames:latest .

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          tags: 'marioguilhermedev/fiapcloudgames:latest'
          push: true

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar depend√™ncias
        run: dotnet restore

      - name: üèóBuild do projeto
        run: dotnet build --configuration Release --no-restore

      - name: Publicar o projeto
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy para o Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: projetofiapcg
          slot-name: production
          package: ./publish
